import { PredictionInput } from '../services/api'

export interface ExampleCompound {
  name: string
  description: string
  data: Partial<PredictionInput>
}

export const exampleCompounds: Record<string, ExampleCompound> = {
  modernInsecticide: {
    name: 'Modern Insecticide (2020)',
    description: 'Neonicotinoid-class insecticide - Expected to be toxic to bees',
    data: {
      source: 'PPDB',
      year: 2020,
      toxicity_type: 'Contact',
      insecticide: 1,
      herbicide: 0,
      fungicide: 0,
      other_agrochemical: 0,
      MolecularWeight: 348.5,
      LogP: 3.2,
      NumHDonors: 1,
      NumHAcceptors: 4,
      NumRotatableBonds: 5,
      AromaticRings: 2,
      NumAromaticRings: 2,
      TPSA: 65.3,
      NumHeteroatoms: 5,
      NumAromaticAtoms: 12,
      NumSaturatedRings: 0,
      NumAliphaticRings: 0,
      RingCount: 2,
      NumRings: 2,
      FractionCsp3: 0.25,
      FractionCSP3: 0.25,
      NumAromaticCarbocycles: 1,
      NumSaturatedCarbocycles: 0,
      MolarRefractivity: 95.5,
      BertzCT: 850.0,
      HeavyAtomCount: 25,
    },
  },
  oldHerbicide: {
    name: 'Old Herbicide (1950)',
    description: 'Pre-1960s herbicide - Expected to be safe for bees',
    data: {
      source: 'ECOTOX',
      year: 1950,
      toxicity_type: 'Oral',
      insecticide: 0,
      herbicide: 1,
      fungicide: 0,
      other_agrochemical: 0,
      MolecularWeight: 221.0,
      LogP: 1.8,
      NumHDonors: 2,
      NumHAcceptors: 3,
      NumRotatableBonds: 2,
      AromaticRings: 1,
      NumAromaticRings: 1,
      TPSA: 42.5,
      NumHeteroatoms: 3,
      NumAromaticAtoms: 6,
      NumSaturatedRings: 0,
      NumAliphaticRings: 0,
      RingCount: 1,
      NumRings: 1,
      FractionCsp3: 0.15,
      FractionCSP3: 0.15,
      NumAromaticCarbocycles: 1,
      NumSaturatedCarbocycles: 0,
      MolarRefractivity: 58.3,
      BertzCT: 420.0,
      HeavyAtomCount: 16,
    },
  },
  safeFungicide: {
    name: 'Safe Fungicide (2010)',
    description: 'Modern fungicide with low toxicity profile',
    data: {
      source: 'PPDB',
      year: 2010,
      toxicity_type: 'Contact',
      insecticide: 0,
      herbicide: 0,
      fungicide: 1,
      other_agrochemical: 0,
      MolecularWeight: 275.3,
      LogP: 2.5,
      NumHDonors: 1,
      NumHAcceptors: 3,
      NumRotatableBonds: 3,
      AromaticRings: 1,
      NumAromaticRings: 1,
      TPSA: 48.2,
      NumHeteroatoms: 4,
      NumAromaticAtoms: 6,
      NumSaturatedRings: 1,
      NumAliphaticRings: 1,
      RingCount: 2,
      NumRings: 2,
      FractionCsp3: 0.35,
      FractionCSP3: 0.35,
      NumAromaticCarbocycles: 1,
      NumSaturatedCarbocycles: 1,
      MolarRefractivity: 72.1,
      BertzCT: 580.0,
      HeavyAtomCount: 20,
    },
  },
  toxicNeonicotinoid: {
    name: 'Toxic Neonicotinoid (2015)',
    description: 'Systemic insecticide - High toxicity to bees',
    data: {
      source: 'PPDB',
      year: 2015,
      toxicity_type: 'Oral',
      insecticide: 1,
      herbicide: 0,
      fungicide: 0,
      other_agrochemical: 0,
      MolecularWeight: 291.7,
      LogP: 0.57,
      NumHDonors: 1,
      NumHAcceptors: 5,
      NumRotatableBonds: 4,
      AromaticRings: 1,
      NumAromaticRings: 1,
      TPSA: 71.8,
      NumHeteroatoms: 6,
      NumAromaticAtoms: 5,
      NumSaturatedRings: 0,
      NumAliphaticRings: 0,
      RingCount: 1,
      NumRings: 1,
      FractionCsp3: 0.33,
      FractionCSP3: 0.33,
      NumAromaticCarbocycles: 0,
      NumSaturatedCarbocycles: 0,
      MolarRefractivity: 71.4,
      BertzCT: 612.5,
      HeavyAtomCount: 21,
    },
  },
  bioInsecticide: {
    name: 'Bio-Insecticide (2018)',
    description: 'Natural origin insecticide - Lower toxicity',
    data: {
      source: 'BPDB',
      year: 2018,
      toxicity_type: 'Contact',
      insecticide: 1,
      herbicide: 0,
      fungicide: 0,
      other_agrochemical: 0,
      MolecularWeight: 394.5,
      LogP: 4.1,
      NumHDonors: 2,
      NumHAcceptors: 6,
      NumRotatableBonds: 8,
      AromaticRings: 0,
      NumAromaticRings: 0,
      TPSA: 88.5,
      NumHeteroatoms: 7,
      NumAromaticAtoms: 0,
      NumSaturatedRings: 2,
      NumAliphaticRings: 2,
      RingCount: 2,
      NumRings: 2,
      FractionCsp3: 0.85,
      FractionCSP3: 0.85,
      NumAromaticCarbocycles: 0,
      NumSaturatedCarbocycles: 2,
      MolarRefractivity: 108.2,
      BertzCT: 720.0,
      HeavyAtomCount: 28,
    },
  },
}

export const exampleOptions = [
  { value: '', label: 'Select an example...' },
  { value: 'modernInsecticide', label: exampleCompounds.modernInsecticide.name },
  { value: 'oldHerbicide', label: exampleCompounds.oldHerbicide.name },
  { value: 'safeFungicide', label: exampleCompounds.safeFungicide.name },
  { value: 'toxicNeonicotinoid', label: exampleCompounds.toxicNeonicotinoid.name },
  { value: 'bioInsecticide', label: exampleCompounds.bioInsecticide.name },
]
